---
title: "Testing and comparing different R packages on random forest algorithm"
author: "Riedlmeier, Moritz; Schröter, Timo; Steins, Patricia; Zinsmeister, Philipp"
date: "August 30, 2024"
output:
  html_notebook:
    toc: true
    number_sections: true
    theme: cosmo
  pdf_document: default
subtitle: RandomForest, ranger & party
bibliography: references.bib
link-citations: true
---

# Introduction

Data scientists, analysts as well as statisticians often face datasets with a large number of variables and observations. This requires not only increasing computational power, but also more efficient methods to handle high-dimensional data and make more accurate variable selection processes to improve predictions. For this purpose, different machine learning methods like decision trees or random forests have been developed. These were first introduced by @breiman1984. They also invented the term classification and regression trees (CART). Nowadays, trees and forests are commonly used procedures to build models for predictions of a variable of interest based on several input variables. They are implemented in statistical software like the R programming language with different packages.

In this paper, three different packages for R that offer solutions for random forests are analyzed. For this purpose, the two most popular packages called “randomForest” and “Ranger” were chosen while also adding “Party” to the repertoire which includes different functions for recursive partitioning. The afore-mentioned packages are benchmarked in terms of their computational performance and their prediction quality. The goal of this paper is to provide an empirically founded recommendation of a single R package to potential users. The preselection of the packages is necessary and based on research. It will be taken up in a dedicated chapter of this paper.

The paper is structured in the following way: firstly, the intuition of tree-structured models and how these are grown is described. After providing comprehension for CART, the theory behind random forests will be covered. In the "Data & Method" chapter of this paper, the structure of the study will be introduced. This is followed by providing background information on the selected R packages and reasons for pre-selecting the afore-mentioned R packages. Finally, the results will be summarized and concluded with recommendations for different use-cases of random forests.

# Theoretical Concepts

In this paper, random forests are used for prediction of categorial data. There will be more details about the data and the motivation in chapter XX. In the following, the theoretical concept of a random forest will be explained. Since tree-based methods are crucial for random forests, there is a previous chapter for the theory of trees. The predictions later are limited to categorial data. Thus, the chapter on tree-based methods are limited to classification trees, too.

## Classification Trees

Classification trees are a type of decision tree used in supervised machine learning to classify data into distinct categories. They are powerful tools for both predictive modeling and data analysis, particularly useful when the outcome variable is categorical. The basic idea behind classification trees is to split the dataset into smaller, more homogeneous groups based on certain criteria, ultimately leading to a decision about the class to which a particular data point belongs [@https://doi.org/10.1007/978-1-0716-1418-1].
The splitting procedure in classification trees is a critical step that determines how the dataset is divided at each node. The goal of splitting is to create groups of data that are as homogeneous as possible with respect to the target variable. The process involves selecting the best feature to split on, which maximizes the distinction between the classes.
For each feature, the algorithm considers all possible splits. For categorical attributes, splits are considered for every possible subset of categories and their impurity is calculated. Impurity is a measure of how mixed the classes are in the dataset. There are different methods to measure the impurity. The Gini index is most commonly used. It is defined as: *INSERT FORMULA*, where phat_{mk} is the proportion of samples that belong to class mk in the node and K is the total number of classes.
The split that results in the lowest impurity is chosen. This process is repeated recursively, splitting each subset further until a stopping criterion (e.g. maximum tree depth or a minimum number of observations per leaf) is met[@https://doi.org/10.1007/978-1-0716-1418-1, @https://doi.org/10.1201/9781315139470].
When built, a classification tree consists of different types of nodes: The tree starts with a root node that represents the entire dataset. This root node is split based on a feature that results in the most significant distinction between the classes. Nodes that result in a pure subset, where all data points belong to the same class, become terminal nodes, also known as leaves. Each leaf represents a final classification decision [@https://doi.org/10.1007/978-1-0716-1418-1, @ https://doi.org/10.1007/BF00116251].
One of the main advantages of classification trees is their interpretability. The visual structure of a tree is easy to understand, making it possible to explain the decision-making process to non-technical stakeholders. Furthermore, classification trees can handle both numerical and categorical data without requiring much preprocessing, such as normalization or scaling.
However, classification trees are not without drawbacks. They are prone to overfitting, especially when the tree grows too deep, capturing noise rather than the underlying pattern. Techniques like pruning, where parts of the tree are removed after the initial training, can help mitigate this problem. Additionally, classification trees may become unstable if small changes in the data lead to different splits and, consequently, different trees. To address this, ensemble methods like random forests are often employed, combining multiple trees to improve accuracy and robustness [@ https://doi.org/10.1007/BF00116251, @https://doi.org/10.1007/978-1-0716-1418-1].

## Random Forests

Random forests are an ensemble learning method that can be used for classification tasks. They are built upon the concept classification trees, but aim to improve accuracy and robustness by combining multiple trees into a single model. This approach mitigates some of the key weaknesses of individual decision trees, such as overfitting and instability. Each tree in the forest is trained on a random subset of the data and a random subset of features. The final prediction is made by aggregating the predictions of all trees, typically through majority voting in classification tasks.
The random forest algorithm starts by creating multiple training datasets using a method called bootstrap sampling. This involves randomly sampling the original dataset with replacement, meaning that some data points may appear multiple times in a sample, while others may not appear at all. Each of these bootstrapped datasets is used to train a different decision tree in the forest.
When splitting nodes in each tree, random forests add another layer of randomness by selecting a random subset of features (typically the square root of the total number of features) to consider for the split. This helps ensure that the trees are diverse, reducing the correlation between them and improving the robustness of the final model.
Each decision tree in the forest is grown to its full depth without pruning. This allows each tree to capture detailed patterns in the data, though it may overfit on its own. However, since each tree is trained on a slightly different dataset and set of features, their errors tend to cancel each other out when combined [@https://doi.org/10.1007/978-1-0716-1418-1].
After all trees have been trained, the random forest makes predictions by aggregating the outputs of the individual trees. The forest's prediction is the class that receives the majority of votes from the trees.
By averaging the predictions of multiple trees, Random Forests tend to achieve higher accuracy than a single decision tree. This is because they reduce variance without substantially increasing bias. The randomness introduced by both bootstrap sampling and random feature selection helps prevent overfitting and the prediction is more generalized. Random forests are also more robust to noise or outliers in the data, since each tree sees only a subset of the data and features, so no single tree can dominate the predictions based on anomalies. In addition, random forests provide a measure of feature importance, indicating which features are most influential in making predictions. This is calculated based on how much each feature reduces impurity across the grown trees.
Random forests have a couple of disadvantages though. First, training a large number of trees can lead to tremendous need of computational resources, especially with high-dimensional data, where random forests are designed for. Since random forests require storing multiple trees, they can be particularly memory-intensive. Furthermore, while individual decision trees are easy to interpret, fandom forests, are more complex and less transparent. For the overall model it's harder to trace the exact decision-making process [@https://doi.org/10.1007/978-1-0716-1418-1, @https://doi.org/10.1023/A:1010933404324 , @https://doi.org/10.1007/978-0-387-84858-7 ].


# Data & method

## Organisation of the study

In line with the research question, empirical and simulated multinomial data is used while drawing on different implementations of the Random Forests algorithm to classify this data. Since the focus lies on comparing different R packages, different goodness of fit measures are considered after classification to evaluate the performance of the R packages. On the basis of the theory and the available information on the packages, it is expected that the Random Forests implementations perform similar across the different packages.

## Data preparation

For the analysis, on the one hand, empirical data is used. The data set originally stems from a project at the Colorado State University and was later donated to the UC Irvine Machine Learning Repository [@blackard]. The data set contains data on cover tree types and surrounding characteristics. In forestry, a cover tree type is determined by the most prevalent tree type in a certain forest area [@gislason2006]. Since the data set contains not only a large amount of observations but also many predictors, it is suitable for the use in the study. As the format of the data set matches the use in the study, the preparation of the data was only made on a small scale. <br><br> On the other hand, simulated data was used for which it is also aimed at arriving at a large number of observations and predictors. In the following, the simulation of the second data set is described where this study draws on the specifically for this purpose created function `gen_dataset`. To get artificial multinomial data and predictor variables, random draws from different **?probability density distributions?**, including the normal, the beta and the uniform distribution, are used. The simulated multinomial data then consists of seven different tree types, on the one hand. On the other hand, a large number of predictors is obtained. Moreover, correlations between the predictors were included in the simulation process as these are expected to be found in an empirical data set. The code generates a vector of random values between `min_cor` and `max_cor` which are both specified manually in advance. It then assigns a random index from remaining variables for each variable to create correlations. Afterwards, observations are selected based on the absolute value of the correlation. If the correlation is positive, the values of the variable are positively correlated with the chosen variable; if negative, they are negatively correlated.

## The different packages

As the focus in this study lies on comparing different R packages, a short introduction to each of the packages is needed. Each package has its own underlying philosophy. First, the *randomForest*-package is described, followed by *ranger* and lastly, the *party*-package [@hothorn2005] is introduced.

### randomForest

The package *randomForest* draws on the original algorithm described in @breiman2001 and originally published in Fortran [@breiman2002]. The type of dependent variable which is to be predicted determines whether classification or regression is performed using the random forest algorithm. In addition, various hyperparameters of the algorithm can be defined: for example, it is possible to specify how many variables are randomly selected at each split of the single trees (hyperparameter `mtry`). Moreover, mathematically interesting is the use of $\sqrt p$ as the default hyperparameter in classification. The *randomForest*-package can be regarded as one of the standard packages implementing the random forest algorithm, which is one of the reasons for using the package in this study.

### ranger

The package random forest generator (known as “Ranger”) package is an implementation for random forests with optimizations for high dimensional data in R. The developers Wright and Ziegler (2017: 2) claim to provide a package which is comparable simple to use. The package is optimized by extensive memory profiling for different types of input data. In contrast to the package Willows, Ranger is able to handle a larger number of features at the same time. As a random forest is proceeded in R, all values of all features of mtry are splitting candidates. Since the required computational power increases exponentially with added features, this is the bottleneck for many random forest packages and the developers of the ranger package focused on this problem. The ranger() function is used to grow a forest and makes use of two different algorithms for the splitting process. At first, the feature values are sorted and accessed by their index. In the second algorithm, the values are sorted and retrieved while splitting. Other than the package RandomForest, Ranger is license free and the software is open-source released which improves traceability of the functions for users on the one hand and accessible for implementation of new features by other developers on the other hand (Wright and Ziegler, 2017: 2 f.). It stands out, that the code for ranger is written in C++ and uses standard libraries only. C++ is described as a low-level language, which expresses in a machine-oriented design and more efficient use of memory (Haidl and Gorlatch, 2018). This makes parallel processing available and considerably accelerates the runtime. Besides from CART, survival trees are also supported by the ranger package.

### party

The documentation of the *party*-package states differences to the *randomForest*-package in the basic implementation, i.e. different base learners were used [@hothorn2005, p. 6]. Whereas the *randomForest*-package draws on Classification and Regression Trees (CART) to form a random forest, the *party*-package utilizes conditional inference trees designed to prevent overfitting and **?variable selection bias?** while combining statistical testing and the basic ideas of CART [@hothorn2006]. Also, the default of the hyperparameters are slightly different to the *randomForest*-package. For example, the default value of `mtry` equals $5$ while in *randomForest* $\sqrt p$ is specified.

## Cross-validation

For the cross-validation, a function `cv_rf` is created to apply classification by the Random Forests algorithm, while drawing on the methods implemented in the R packages described in section 3.3: `randomForest`, `ranger`, and `cforest`. With `cv_rf`, the models' performance based on accuracy, F1 score, and F-beta score, while also recording the computational time taken to fit each model.

By using parallelization techniques, various hyperparameter combinations (`ntree` and `mtry` are efficiently tested. The function is run across all combinations while collecting the results for further analysis.

The cross-validation is targeted at obtaining the optimal hyperparameter combinations as measured in different goodness-of-fit indicators for each type of data, empirical as well as simulated data,.

# Results

# Conclusion

# References
